package in.touriga.tourigabackend.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Document(collection = "Packagedetails")
public class Package {
	@Id
    private String packageid;
    private String packagename;
    private String placename;
    public String getPackageid() {
		return packageid;
	}
	public String getPlacename() {
		return placename;
	}
	public void setPlacename(String placename) {
		this.placename = placename;
	}
	public void setPackageid(String packageid) {
		this.packageid = packageid;
	}
	private String description;
    public String getPackagename() {
		return packagename;
	}
	public void setPackagename(String packagename) {
		this.packagename = packagename;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public String getDuration() {
		return duration;
	}
	public void setDuration(String duration) {
		this.duration = duration;
	}
	public Integer getCost() {
		return cost;
	}
	public void setCost(Integer cost) {
		this.cost = cost;
	}
	public String getCitescover() {
		return citescover;
	}
	public void setCitescover(String citescover) {
		this.citescover = citescover;
	}
	public String getImg_src() {
		return img_src;
	}
	public void setImg_src(String img_src) {
		this.img_src = img_src;
	}
	private String duration;
    private Integer cost;
    private String citescover;
    private String img_src;
    
}

    // Getters and setters (generated by Lombok)

    // No-args constructor (generated by Lombok)

    // All-args constructor (generated by Lombok)

    // Other methods as needed
