package in.touriga.tourigabackend.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Document(collection = "Placedetails")
public class Place {
	@Id
    private String placeid;
    private String placename;
    private String description;
    private String map_src;
    private String img_src;
	public String getPlacename() {
		return placename;
	}
	public void setPlacename(String placename) {
		this.placename = placename;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public String getMap_src() {
		return map_src;
	}
	public void setMap_src(String map_src) {
		this.map_src = map_src;
	}
	public String getImg_src() {
		return img_src;
	}
	public void setImg_src(String img_src) {
		this.img_src = img_src;
	}
    
    // Getters and setters (generated by Lombok)

    // No-args constructor (generated by Lombok)

    // All-args constructor (generated by Lombok)

    // Other methods as needed
}
